version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    # environment:
    #   POSTGRES_USER: myuser
    #   POSTGRES_PASSWORD: mypassword
    #   POSTGRES_DB: mydatabase
    ports:
      - "9001:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/bouhammo/db

networks:
  backend:
    driver: bridge